export interface Creature {
  emoji: string;
  name: string;
}

// 可愛的動物、昆蟲、海洋生物，依序解鎖收集
export const CREATURES: Creature[] = [
  { emoji: "🐶", name: "小狗" },
  { emoji: "🐱", name: "小貓" },
  { emoji: "🐰", name: "兔子" },
  { emoji: "🦊", name: "狐狸" },
  { emoji: "🐼", name: "貓熊" },
  { emoji: "🐨", name: "無尾熊" },
  { emoji: "🦁", name: "獅子" },
  { emoji: "🐯", name: "老虎" },
  { emoji: "🐵", name: "猴子" },
  { emoji: "🦒", name: "長頸鹿" },
  { emoji: "🦝", name: "浣熊" },
  { emoji: "🦦", name: "水獺" },
  { emoji: "🐝", name: "蜜蜂" },
  { emoji: "🐞", name: "瓢蟲" },
  { emoji: "🦋", name: "蝴蝶" },
  { emoji: "🐛", name: "毛毛蟲" },
  { emoji: "🐜", name: "螞蟻" },
  { emoji: "🦗", name: "蟋蟀" },
  { emoji: "🐠", name: "熱帶魚" },
  { emoji: "🐡", name: "河豚" },
  { emoji: "🐬", name: "海豚" },
  { emoji: "🐳", name: "鯨魚" },
  { emoji: "🐙", name: "章魚" },
  { emoji: "🦐", name: "小蝦" },
  { emoji: "🦀", name: "螃蟹" },
  { emoji: "🐢", name: "海龜" },
  { emoji: "🦭", name: "海豹" },
  { emoji: "🐚", name: "貝殼" },
  { emoji: "🐹", name: "倉鼠" },
  { emoji: "🐭", name: "老鼠" },
  { emoji: "🐻", name: "小熊" },
  { emoji: "🐻‍❄️", name: "北極熊" },
  { emoji: "🐮", name: "乳牛" },
  { emoji: "🐷", name: "小豬" },
  { emoji: "🐸", name: "青蛙" },
  { emoji: "🐴", name: "小馬" },
  { emoji: "🦄", name: "獨角獸" },
  { emoji: "🦓", name: "斑馬" },
  { emoji: "🦌", name: "小鹿" },
  { emoji: "🐘", name: "大象" },
  { emoji: "🦏", name: "犀牛" },
  { emoji: "🦛", name: "河馬" },
  { emoji: "🐪", name: "駱駝" },
  { emoji: "🦙", name: "羊駝" },
  { emoji: "🐑", name: "綿羊" },
  { emoji: "🐐", name: "山羊" },
  { emoji: "🦘", name: "袋鼠" },
  { emoji: "🦫", name: "海狸" },
  { emoji: "🦔", name: "刺蝟" },
  { emoji: "🦇", name: "蝙蝠" },
  { emoji: "🐺", name: "野狼" },
  { emoji: "🐔", name: "母雞" },
  { emoji: "🐓", name: "公雞" },
  { emoji: "🐥", name: "小雞" },
  { emoji: "🐦", name: "小鳥" },
  { emoji: "🦅", name: "老鷹" },
  { emoji: "🦆", name: "鴨子" },
  { emoji: "🦢", name: "天鵝" },
  { emoji: "🦉", name: "貓頭鷹" },
  { emoji: "🦚", name: "孔雀" },
  { emoji: "🦜", name: "鸚鵡" },
  { emoji: "🦩", name: "紅鶴" },
  { emoji: "🐧", name: "企鵝" },
  { emoji: "🐍", name: "小蛇" },
  { emoji: "🦎", name: "蜥蜴" },
  { emoji: "🐊", name: "鱷魚" },
  { emoji: "🐉", name: "神龍" },
  { emoji: "🦕", name: "長頸龍" },
  { emoji: "🦖", name: "暴龍" },
  { emoji: "🦈", name: "鯊魚" },
  { emoji: "🦞", name: "龍蝦" },
  { emoji: "🦑", name: "魷魚" },
  { emoji: "🪼", name: "水母" },
  { emoji: "🐌", name: "蝸牛" },
  { emoji: "🦂", name: "蠍子" },
  { emoji: "🕷️", name: "蜘蛛" },
];

export const POINTS_PER_CREATURE = 5;
export const CREATURE_COUNT = CREATURES.length;
