export interface Decoration {
  id: string;
  name: string;
  emoji: string;
  price: number;
}

export const DECORATIONS: Decoration[] = [
  { id: "fence_wood", name: "木柵欄", emoji: "🪵", price: 1 },
  { id: "fence_stone", name: "石磚牆", emoji: "🧱", price: 1 },
  { id: "fence_picket", name: "施工圍欄", emoji: "🚧", price: 1 },
  { id: "rock", name: "大石頭", emoji: "🪨", price: 1 },
  { id: "mushroom", name: "小蘑菇", emoji: "🍄", price: 1 },
  { id: "shamrock", name: "幸運草", emoji: "☘️", price: 1 },
  { id: "flower_rose", name: "紅玫瑰", emoji: "🌹", price: 1 },
  { id: "flower_sunflower", name: "向日葵", emoji: "🌻", price: 1 },
  { id: "flower_tulip", name: "鬱金香", emoji: "🌷", price: 1 },
  { id: "flower_lotus", name: "蓮花", emoji: "🪷", price: 2 },
  { id: "flower_blossom", name: "櫻花", emoji: "🌸", price: 2 },
  { id: "maple_leaf", name: "楓樹", emoji: "🍁", price: 2 },
  { id: "bamboo", name: "竹林", emoji: "🎍", price: 2 },
  { id: "cactus", name: "仙人掌", emoji: "🌵", price: 2 },
  { id: "tree_pine", name: "松樹", emoji: "🌲", price: 2 },
  { id: "tree_oak", name: "大榕樹", emoji: "🌳", price: 2 },
  { id: "tree_palm", name: "椰子樹", emoji: "🌴", price: 2 },
  { id: "tree_xmas", name: "聖誕樹", emoji: "🎄", price: 4 },
  { id: "bench", name: "公園椅", emoji: "🪑", price: 2 },
  { id: "signpost", name: "指路牌", emoji: "🪧", price: 2 },
  { id: "mailbox", name: "紅郵筒", emoji: "📮", price: 2 },
  { id: "lantern", name: "紅燈籠", emoji: "🏮", price: 2 },
  { id: "umbrella", name: "海灘傘", emoji: "⛱️", price: 2 },
  { id: "balloon", name: "氣球", emoji: "🎈", price: 1 },
  { id: "kite", name: "風箏", emoji: "🪁", price: 2 },
  { id: "gift_box", name: "神秘禮物", emoji: "🎁", price: 2 },
  { id: "fountain", name: "小噴泉", emoji: "⛲", price: 3 },
  { id: "camping_fire", name: "溫暖營火", emoji: "🔥", price: 3 },
  { id: "snowman", name: "雪人", emoji: "⛄", price: 3 },
  { id: "boat_canoe", name: "獨木舟", emoji: "🛶", price: 3 },
  { id: "boat_sail", name: "小帆船", emoji: "⛵", price: 4 },
  { id: "mountain", name: "假山造景", emoji: "⛰️", price: 4 },
  { id: "hot_spring", name: "溫泉", emoji: "♨️", price: 5 },
  { id: "telescope", name: "天文望遠鏡", emoji: "🔭", price: 5 },
  { id: "moai", name: "摩艾石像", emoji: "🗿", price: 5 },
  { id: "tent", name: "露營帳篷", emoji: "⛺", price: 5 },
  { id: "house_hut", name: "茅草屋", emoji: "🛖", price: 5 },
  { id: "house_wood", name: "木造小屋", emoji: "🏠", price: 5 },
  { id: "house_brick", name: "磚瓦別墅", emoji: "🏡", price: 6 },
  { id: "crystal_ball", name: "魔法水晶", emoji: "🔮", price: 6 },
  { id: "torii", name: "鳥居", emoji: "⛩️", price: 8 },
  { id: "carousel", name: "旋轉木馬", emoji: "🎠", price: 8 },
  { id: "volcano", name: "小火山", emoji: "🌋", price: 8 },
  { id: "ferris_wheel", name: "摩天輪", emoji: "🎡", price: 10 },
  { id: "tokyo_tower", name: "鐵塔", emoji: "🗼", price: 10 },
  { id: "circus", name: "馬戲團", emoji: "🎪", price: 10 },
  { id: "roller_coaster", name: "雲霄飛車", emoji: "🎢", price: 12 },
  { id: "castle", name: "夢幻城堡", emoji: "🏰", price: 15 },
  { id: "fuji", name: "富士山", emoji: "🗻", price: 15 },
  { id: "trophy", name: "冠軍金盃", emoji: "🏆", price: 20 }
];